import UIKit

/// A bundled "따라 그리기" guide set: a short sequence of light line-art pages.
/// The kid traces each page; on playback the guides are hidden, so only the
/// child's own drawing animates — rotoscoping without knowing the word.
struct GuidePreset: Identifiable {
    /// Bundle folder name (e.g. "02_bunny"). Persisted in project.json so a
    /// saved project can find its guides again.
    let id: String
    let frameURLs: [URL]

    /// Drawing surface size, taken from the first guide image.
    var canvasSize: CGSize {
        guard let first = frameURLs.first,
              let img = UIImage(contentsOfFile: first.path) else {
            return RotoProject.blankCanvasSize
        }
        return img.size
    }

    /// Mid-animation frame — usually the most recognizable pose.
    var thumbnail: UIImage? {
        guard !frameURLs.isEmpty else { return nil }
        return UIImage(contentsOfFile: frameURLs[frameURLs.count / 2].path)
    }

    func image(forScene i: Int) -> UIImage? {
        guard frameURLs.indices.contains(i) else { return nil }
        return UIImage(contentsOfFile: frameURLs[i].path)
    }
}

/// Loads the guide sets bundled under Resources/Presets. Each set is a folder
/// of frame_NN.png files; folder name order (01_…, 02_…) is display order.
/// Generated by Tools/generate_presets.py — swap the PNGs to change the art.
enum PresetLibrary {
    static let all: [GuidePreset] = load()

    static func preset(id: String) -> GuidePreset? {
        all.first { $0.id == id }
    }

    private static func load() -> [GuidePreset] {
        let fm = FileManager.default
        guard let root = Bundle.main.resourceURL?
            .appendingPathComponent("Presets", isDirectory: true),
              let folders = try? fm.contentsOfDirectory(at: root,
                                                        includingPropertiesForKeys: nil)
        else { return [] }

        return folders
            .filter(\.hasDirectoryPath)
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
            .compactMap { folder in
                guard let files = try? fm.contentsOfDirectory(at: folder,
                                                              includingPropertiesForKeys: nil)
                else { return nil }
                let frames = files
                    .filter { $0.pathExtension.lowercased() == "png" }
                    .sorted { $0.lastPathComponent < $1.lastPathComponent }
                guard !frames.isEmpty else { return nil }
                return GuidePreset(id: folder.lastPathComponent, frameURLs: frames)
            }
    }
}
